# Generated by Django 3.1.4 on 2020-12-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=15)),
                ('currentBalance', models.IntegerField()),
                ('lastTransaction', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('InterestRate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('managerName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceAccount', models.BigIntegerField()),
                ('destAccount', models.BigIntegerField()),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('interestRate', models.FloatField()),
                ('loanPeriod', models.TimeField()),
                ('remainingTerms', models.IntegerField()),
                ('accountNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('contactNo', models.BigIntegerField()),
                ('address', models.CharField(max_length=40)),
                ('accountNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.accounts')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.accounttype'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.branch'),
        ),
    ]
