# Generated by Django 3.1.4 on 2020-12-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20201217_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
