# Generated by Django 3.1.4 on 2020-12-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20201217_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='lastTransaction',
        ),
    ]
