# Generated by Django 3.1.4 on 2021-02-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_account_lasttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destAccount',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sourceAccount',
            field=models.BigIntegerField(blank=True),
        ),
    ]
