# Generated by Django 3.1.4 on 2021-02-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20210206_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destAccount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sourceAccount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
