# Generated by Django 3.1.4 on 2021-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20210206_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currentBalance',
            field=models.IntegerField(null=True),
        ),
    ]
