# Generated by Django 3.1.4 on 2021-02-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20210206_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currentBalance',
        ),
    ]
