# Generated by Django 3.1.4 on 2021-02-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_account_currentbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='profile_pic',
            new_name='Employee_Photo',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='facebook_id',
            new_name='LinkedIn_ID',
        ),
    ]
