# Generated by Django 3.1.4 on 2021-02-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20210206_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
